package it.polimi.ingsw.network.enums;

public enum Message {
    HELP, LOGIN, DISCONNECT, SHOW,
    MOVE, GRAB, SHOOT, NOTIFY,
    MESSAGE, COLOR, MOVE_GRAB,
    USERNAME, PLAYER, END_TURN,
    NEW_TURN, GAME, RECONNECTION,
    SPAWN, SQUARE, POWERUP,
    POWERUP_AMMOS, RELOAD,
    SQUARE_2, BOARD, SCORE, DROP,
    FINAL_FRENZY, MOVE_RELOAD, NOT_TURN,
    DROP_POWERUP, DROP_WEAPON, DISCARD_POWERUP, DISCARD_WEAPON;

}
